# Confirms that community-version will run without crashing
on:
  pull_request:
    branches: [master]

jobs:
  test-community-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: remove output.txt if it exists
        run: |
          output=$(ls | grep output.txt || true)
          if ! [ -z output ]; then
            rm output.txt
          fi
      - name: run community version
        run: python3 community-version.py example/ztm-logo.png
      - name: confirm output.txt is created
        run: |
          output=$(ls | grep output.txt || true)
          if [ -z output ]; then
            echo "no output.txt file was created. failing build..."
            exit 1
          fi
